# This is a basic workflow to help you get started with Actions
name: Add to Project
on:
  issues:
    types:
      - labeled
jobs:
  add-to-art:
    if: github.event.label.name == 'Art'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Art
          column: To Do
          repo-token: ${{ secrets.ACCESS_TOKEN }}

  add-to-code:
    if: github.event.label.name == 'Programming'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Code
          column: To Do
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          
          
  add-to-design:
    if: github.event.label.name == 'Design'
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: Design
          column: To Do
          repo-token: ${{ secrets.ACCESS_TOKEN }}
