# This is a basic workflow to help you get started with Actions
name: Add to Project
on:
  issues:
    types:
      - labeled
jobs:
  add-to-art:
    if: github.event.label.name == 'Art'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Issue to Project
        # You may pin to the exact commit or the version.
        # uses: monry/actions-add-issue-to-project@3e54e1f966203c08d6f15406f7dcf6f6ef2f7dd1
        uses: monry/actions-add-issue-to-project@v1
        with:
          # Personal Access Token that with `repo`, `org:read` and `org:write` are granted.
          github-token: ${{ secrets.ACCESS_TOKEN }}
          project-owner: 'monry'
          project-number: 1
          issue-id: ${{ github.event.issue.node_id }}

  add-to-code:
    if: github.event.label.name == 'Programming'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Issue to Project
        # You may pin to the exact commit or the version.
        # uses: monry/actions-add-issue-to-project@3e54e1f966203c08d6f15406f7dcf6f6ef2f7dd1
        uses: monry/actions-add-issue-to-project@v1
        with:
          # Personal Access Token that with `repo`, `org:read` and `org:write` are granted.
          github-token: ${{ secrets.ACCESS_TOKEN }}
          project-owner: 'monry'
          project-number: 1
          issue-id: ${{ github.event.issue.node_id }}
          
          
  add-to-design:
    if: github.event.label.name == 'Design'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add Issue to Project
        # You may pin to the exact commit or the version.
        # uses: monry/actions-add-issue-to-project@3e54e1f966203c08d6f15406f7dcf6f6ef2f7dd1
        uses: monry/actions-add-issue-to-project@v1
        with:
          # Personal Access Token that with `repo`, `org:read` and `org:write` are granted.
          github-token: ${{ secrets.ACCESS_TOKEN }}
          project-owner: 'monry'
          project-number: 1
          issue-id: ${{ github.event.issue.node_id }}
