name: Set Priority
on:
  project_card:
    types:
      - moved
jobs:
  label_issues:
    if: github.event.project_card.name == 'High Priority'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "High Priority"
          repo-token: ${{ secrets.ACCESS_TOKEN }}
